merge fonction calculDesValeurs
RobinAlonzo/S3.01_Developpement_d_application_et_Gestion_de_projet pull request #6
Opened 2022-12-15 12:49 UTC by Nicolas-Delahaie

Voici la simple recopie de l'algo,
a corriger pour qu'il corresponde aux attentes

2022-12-15 17:46 UTC, RobinAlonzo commented on PoleDeveloppement/src/fonctions/calculDesValeurs.php
> +    //Autres valeurs
Si tu peux juste commenter un peut plus cette partie pour que l'on comprenne ce que c'est stp.

2022-12-20 16:17 UTC, oiercesat commented
toujours pas bon car ne suis pas l'algo à  la lettre et les points doivent se transformer en ->

2022-12-20 16:51 UTC, RobinAlonzo commented on PoleDeveloppement/src/fonctions/calculDesValeurs.php
> +            if ($recettePossibles[$j].getQtRecette() > $recettesPossibles[$j+1].getQtRecette()){
`($recettePossibles[$j]->getQtRecette() > $recettesPossibles[$j+1]->getQtRecette())`

2022-12-20 16:52 UTC, RobinAlonzo commented on PoleDeveloppement/src/fonctions/calculDesValeurs.php
> +    $recettesPossibles[0].setValeur($valeur);
`$recettesPossibles[0]->setValeur($valeur)`

2022-12-20 16:52 UTC, RobinAlonzo commented on PoleDeveloppement/src/fonctions/calculDesValeurs.php
> +        if ($recettesPossibles[$i].getQtRecette() == $recettesPossibles[$i-1].getQtRecette()){
`($recettesPossibles[$i]->getQtRecette() == $recettesPossibles[$i-1]->getQtRecette())`

2022-12-20 16:53 UTC, RobinAlonzo commented on PoleDeveloppement/src/fonctions/calculDesValeurs.php
> +            $recettesPossibles[$i].setValeur($valeur);
`$recettesPossibles[$i]->setValeur($valeur)`

2022-12-20 16:53 UTC, RobinAlonzo commented on PoleDeveloppement/src/fonctions/calculDesValeurs.php
> +            $recettesPossibles[$i].setValeur($valeur);
`$recettesPossibles[$i]->setValeur($valeur)`

2022-12-20 16:54 UTC, RobinAlonzo requested changes
Je t'ai mis des commentaires sur ton commit, regarde directement dans le fichier ^^

2023-01-03 14:28 UTC, oiercesat commented
c'est valeur--

2023-01-03 14:29 UTC, oiercesat commented
sur la ligne 45

2023-01-03 15:47 UTC, oiercesat approved these changes
c'est bon

2023-01-03 15:47 UTC, RobinAlonzo approved these changes

2023-01-03 15:47 UTC, merged